### ISSUE TITLE
Skylanders Spyro's Adventure PC (not the right place to ask, sorry)

### ISSUE THREAD

**Issue by diosmio22** [c272/algo-lang#9]
Hello c272, sorry if I'm contacting you through the bug reports on github, but your discord listed on the files archive (https://lostfilearchives.github.io/contact/) isn't available, and also you don't seem to answer my email. Sorry again to ask you this here, but can you send the files for Skylanders Spyro's adventure PC? You seem to be the only person in the whole internet that has it. Really.
Have a good one, hope you can help me.

**Comment by c272** [comment]
Hi Diosmio,

Sorry my contact information was out of date. I store games for purely archiving purposes, so unless you also own a physical copy, I'm afraid giving you a download link would equate to piracy.

If you can find a copy of the physical PC version floating around (there were a few, at least a few years ago), then you can rip it from disc with a good enough DVD ripper. You need to make sure it has proper MDS/MDX support though.

I sincerely hope you find/have found what you're looking for.
